const Response = {
    NONE: 0,

    HOST_GAME_ROOM_CREATED_SUCCESSFULLY: 1,
    HOST_FAILED_TO_CREATE_GAME_ROOM: 2,

    HOST_PLAYER_KICKED_SUCCESSFULLY: 3,
    HOST_FAILED_TO_KICK_PLAYER: 4,

    HOST_STARTED_GAME_SUCCCESSFULLY: 5,
    HOST_FAILED_TO_START_GAME: 6,

    HOST_GAME_TIMER_SYNCED_SUCCCESSFULLY: 7,
    HOST_FAILED_TO_SYNC_GAME_TIMER: 8,

    HOST_GAME_ENDED_SUCCCESSFULLY: 9,
    HOST_FAILED_TO_END_GAME: 10,

    
    CLIENT_JOINED_GAME_ROOM_SUCCESSFULLY: 11,
    CLIENT_FAILED_TO_JOIN_GAME_ROOM: 12,

    CLIENT_LEFT_GAME_ROOM_SUCCCESSFULLY: 13,
    CLIENT_FAILED_TO_LEAVE_GAME_ROOM: 14,

    CLIENT_GAME_STARTED_BY_HOST: 15,
    CLIENT_ROOM_CLOSED_BY_HOST: 16,

    CLIENT_RECEIVE_GAME_TIMER: 17,
    CLIENT_GAME_ENDED: 18,

    OTHER_PLAYER_JOINED_GAME_ROOM: 19,
    OTHER_PLAYER_LEFT_GAME_ROOM: 20,

    PLAYER_SCORE_AND_WORD_UPDATED_SUCCCESSFULLY: 21,
    FAILED_TO_UPDATE_GAME_SCORE_AND_WORD: 22,

    RECEIVE_OTHER_PLAYERS_SCORE: 23,

    RECIEVE_ALL_ROOM_DATA: 24,
}

module.exports = {
    Response
}