const Response = {
    NONE: 0,

    HOST_GAME_ROOM_CREATED_SUCCESSFULLY: 1,
    HOST_FAILED_TO_CREATE_GAME_ROOM: 2,

    HOST_PLAYER_KICKED_SUCCESSFULLY: 3,
    HOST_FAILED_TO_KICK_PLAYER: 4,

    HOST_STARTED_GAME_SUCCCESSFULLY: 5,
    HOST_FAILED_TO_START_GAME: 6,
    
    CLIENT_JOINED_GAME_ROOM_SUCCESSFULLY: 7,
    CLIENT_FAILED_TO_JOIN_GAME_ROOM: 8,

    CLIENT_LEFT_GAME_ROOM_SUCCCESSFULLY: 9,
    CLIENT_FAILED_TO_LEAVE_GAME_ROOM: 10,

    OTHER_PLAYER_JOINED_GAME_ROOM: 11,
    OTHER_PLAYER_LEFT_GAME_ROOM: 12,

    RECIEVE_ALL_ROOM_DATA: 13,

    All_PLAYERS_LOADED: 14, 

    ALL_PLAYERS_DONE_WITH_ACTION: 15,

    OTHER_PLAYER_DRAWS_CARD: 16,
    OTHER_PLAYER_RETURNS_CARD: 17,
    OTHER_PLAYER_DRAWS_AND_EXCHANGES: 18,

    OTHER_PLAYER_IS_TRADING: 19,
    OTHER_PLAYER_REQUESTED_CARD: 20, 
    ALL_TRADING_PLAYERS_RECIEVED: 21,
    OTHER_PLAYER_COULD_NOT_TRADE: 22,
    OTHER_PLAYER_CHOSE_PLAYER_TO_TRADE: 23,
    OTHER_PLAYER_ANSWERED_QUESTION: 24,
    OTHER_PLAYER_CHOSE_CARD_TO_KEEP_BACK: 25,

    OTHER_PLAYER_MAKING_WORD: 26,
    OTHER_PLAYER_MADE_WORD: 27,

    GAME_END: 28,
}

module.exports = {
    Response
}